### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by NicklausBrain** [NicklausBrain/ai-flashcards#88]
```
dbug: Microsoft.AspNetCore.SignalR.HubConnectionHandler[6]
      OnConnectedAsync ending.
warn: Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer[100]
      Unhandled exception rendering component: An item with the same key has already been added. Key: nägi
      System.ArgumentException: An item with the same key has already been added. Key: nägi
         at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
         at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] source, Func`2 keySelector, IEqualityComparer`1 comparer)
         at My1kWordsEe.Models.Games.Word2WordMatchGame..ctor(Pair[] pairs)
         at My1kWordsEe.Models.Games.Word2WordMatchGame.<>c__DisplayClass22_0.<<Generate>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at My1kWordsEe.Components.Pages.Games.Word2WordMatchGamePage.OnParametersSetAsync()
         at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
         at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
         at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by NicklausBrain** [comment]
fixed here: https://github.com/NicklausBrain/ai-flashcards/pull/85
